version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wallet_alkemy
      - POSTGRES_USER=ben
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=heroku_39ff028ba999390
      - MYSQL_USER=bd8f774d0ac1ad
      - MYSQL_ROOT_PASSWORD=e7446036
      - MYSQL_PORT=3306
      - MYSQL_HOST=us-cdbr-east-05.cleardb.net
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
